### ISSUE TITLE
What ruff version is used?

### ISSUE THREAD

**Issue by calebAtIspot** [astral-sh/ruff-pre-commit#104]
I'm really confused as to what ruff version is being used, because it looks like this installs ruff for you but I don't see where it does that. So, two questions I guess - what version and how is it installed?

**Comment by zanieb** [comment]
The Ruff version matches the tag in this repository, so, from the `README`:

```
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.4
```

The `v0.7.4` tag from here is cloned which uses Ruff v0.7.4

**Comment by calebAtIspot** [comment]
Thanks!
