### ISSUE TITLE
Nix: No such file or directory: '~/.cache/pre-commit/...python3.10/bin/ruff'

### ISSUE THREAD

**Issue by MatrixManAtYrService** [astral-sh/ruff-pre-commit#22]
I'm working on a project which uses ruff via pre-commit.  I've simplified the `.pre-commit-config.yaml` to the following:

```
---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.229'
    hooks:
      - id: ruff
```

When I run `pre-commit run --all-files` I get the following:

```
 ❯ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/charliermarsh/ruff-pre-commit.
[INFO] Installing environment for https://github.com/charliermarsh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

[Errno 2] No such file or directory: '/home/matt/.cache/pre-commit/repo2mikycmg/py_env-python3.10/bin/ruff'
```

Which is weird, because that file definitely exists.

This is on my Linux machine (NixOS 23.05).  I've been working around it by just doing the linting on macOS, but that's kind of a pain.  Any idea what I can do to fix this?

**Comment by charliermarsh** [comment]
Could this be related to https://github.com/charliermarsh/ruff/issues/1699?

**Comment by MatrixManAtYrService** [comment]
Seems likely, I have that same experience:
```
❯ nix-shell -p python311
[nix-shell:~/2023/01/21]$ python -m venv venv
[nix-shell:~/2023/01/21]$ source venv/bin/activate

[nix-shell:~/2023/01/21]$ pip install ruff
Collecting ruff
  Using cached ruff-0.0.229-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
Installing collected packages: ruff
Successfully installed ruff-0.0.229

[nix-shell:~/2023/01/21]$ ruff
bash: /home/matt/2023/01/21/venv/bin/ruff: No such file or directory
```

**Comment by AntonLydike** [comment]
There is a workaround, but it's really really ugly:

```bash
rm '<offending ruff binary>'
ln -s $(which ruff) '<offending ruff binary>'
```

**Comment by TheLostLambda** [comment]
That workaround works, but obviously only until pre-commit regenerates that cache! It would be nice a more proper fix for this at some point :)

**Comment by anund** [comment]
The beginnings of a fix might look like invoking autoPatchelf in the shell hook. 

An example `.pre-commit-config.yaml` that uses ruff
```yaml
---
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.229'
    hooks:
      - id: ruff
```

An example `flake.nix` that add `pre-commit` and a `libgcc` which ruff binary depends on. Note I don't regularly use flakes, this works but may be bad copy+pasta. The important bits are in the shellhook and in `nativeBuildInputs`

```nix
{
  description = "Dev env";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    flake-compat.url = "github:edolstra/flake-compat";
    flake-compat.flake = false;
  };
  outputs = {
    nixpkgs,
    flake-utils,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = import nixpkgs {
        inherit system;
        overlays = [];
      };
    in {
      devShells.default = pkgs.mkShell {
        name = "dev-env";
        buildInputs = with pkgs; [
          pre-commit
          glibc.libgcc
        ];
        nativeBuildInputs = [ pkgs.autoPatchelfHook ];
        shellHook = ''
          pre-commit install
          # oddly the python pre-commit hook doesn't actually install things during install
          # here's a hack to force ruff into the pre-commit cache 
          pre-commit run
          # pre-commits output is a bit verbose when it succeeds, choose your own output wrangling
          patch=$(autoPatchelf ~/.cache/pre-commit/)
          if [[ $? -ne 0 ]]; then
            echo "$patch"
            exit 1
          else
            echo "patched ~/.cache/pre-commit"
          fi
        '';
      };
    });
}
```



Inspiration from https://sandervanderburg.blogspot.com/2018/10/auto-patching-prebuilt-binary-software.html

**Comment by anund** [comment]
I believe this issue can be closed and, perhaps, tracked somewhere more nix specific.

**Comment by MatrixManAtYrService** [comment]
I agree.  This repo is a way to access the problem, but it doesn't itself have a problem.  Let's close it.

**Comment by MatrixManAtYrService** [comment]
If I'm understanding correctly, the "right way" to fix this requires:

1. somebody who cares about nix...
2. ...to go fix the way pip (a python package manager) installs ruff (a program written in rust)

But a big part of the reason to be a 1-type person is because you don't want to deal with 2-type problems anymore.  Maybe our hero is out there.  Maybe they'll fix it the *right way*.  But I'm not going to hold my breath, I'm going to focus on finding a nicer workaround because I'd rather rely on fewer types of binary cache anyhow.

My initial explorations of https://github.com/cachix/pre-commit-hooks.nix indicate that it wants to *replace* pre-commit.  It will say things like this:

> pre-commit-hooks.nix: WARNING: Refusing to install because of pre-existing .pre-commit-config.yaml
>   1. Translate .pre-commit-config.yaml contents to the new syntax in your Nix file
>        see https://github.com/cachix/pre-commit-hooks.nix#getting-started
>    2. remove .pre-commit-config.yaml
>    3. add .pre-commit-config.yaml to .gitignore

My team would not like it if I made that change (they're not all nix users).  But perhaps...

A. ruff can be added to pre-commit-hooks.nix
B. pre-commit-hooks.nix can be... configured? forked? such that it can comfortably share a repo with pre-commit, and instead just overrides certain hooks with its own--which I assume do not involved asking pip to build ruff.

This would solve my problem, but maybe it's overkill?  Maybe it won't solve your problem?  I'm curious if others think it's a sane approach.

**Comment by NickLarsenNZ** [comment]
For anyone coming here still looking for a solution, here's what worked for me:

1. Delete the cached ruff (eg: if you ran the hook before installing it via nixpkgs)
2. Rerun pre-commit (it will not used the cached one, and instead use your installed and correctly linked binary).
