### ISSUE TITLE
Request: automatic update upon new `ruff` release

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/ruff-pre-commit#37]
[`v0.0.268`](https://github.com/charliermarsh/ruff/releases/tag/v0.0.268) was released  about 30-mins ago.  I went to `pre-commit autoupdate` and getting:

```none
[https://github.com/charliermarsh/ruff-pre-commit] already up to date!
```

It would be cool if a `ruff` release would automatically kick off an update here.

Seems like https://github.com/charliermarsh/ruff-pre-commit/issues/17 was about this, but it appears not to have been done

**Comment by edgarrmondragon** [comment]
This is already done: https://github.com/charliermarsh/ruff/blob/a3aa841fc94cdc1973a97446108ae7468e2e9f71/.github/workflows/release.yaml#L409-L411

In this case it seems like the version `v0.0.268` wasn't correctly tagged: https://github.com/charliermarsh/ruff/actions/runs/5017203711/jobs/8995529490#step:4:54

**Comment by charliermarsh** [comment]
This used to work, but it somehow broke silently. I think the API changed or something.

**Comment by charliermarsh** [comment]
Also, I forgot to actually merge the version bump prior to cutting the release, so none of the wheels made it to PyPI 🤦

**Comment by charliermarsh** [comment]
Calling this a bug because it's supposed to work.

**Comment by charliermarsh** [comment]
That's expected though, the release isn't out on PyPI yet.

**Comment by charliermarsh** [comment]
Ok cool, it did run automatically this time as soon as the release hit PyPI: https://github.com/astral-sh/ruff-pre-commit/actions/runs/5072952304/jobs/9111342486

**Comment by charliermarsh** [comment]
Thanks @konstin!
