### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by lukasz-mitka** [astral-sh/ruff-pre-commit#42]
I'm using renovatebot to auto upgrade my pre-commit config.
One thing I'm missing is release notes.

I would appreciate if https://github.com/astral-sh/ruff-pre-commit could:
* create GitHub releases instead of only tags
* copy release notes from https://github.com/astral-sh/ruff release notes
  * or at least include link to them

**Comment by charliermarsh** [comment]
I started creating them: https://github.com/astral-sh/ruff-pre-commit/releases/tag/v0.0.276. Let me know if that works.

**Comment by lukasz-mitka** [comment]
Great, thanks!

Why does release [v0.0.276](https://github.com/astral-sh/ruff-pre-commit/releases/tag/v0.0.276) link to `v0.0.275`?

Looks like it should work well enough with renovate. I'll update once I get a PR.

**Comment by lukasz-mitka** [comment]
Works as expected!

**Comment by lukasz-mitka** [comment]
@charliermarsh can we reopen this? I see new releases without notes link.
It needs to be automated I guess.
