### ISSUE TITLE
Feature Request: Enable GitHub Discussions

### ISSUE THREAD

**Issue by jgarte** [astral-sh/ruff-pre-commit#47]
Hi,

I'd like to request to enable GitHub Discussions for the community to ask questions about `ruff-pre-commit` without polluting the issue tracker.

WDYT

**Comment by zanieb** [comment]
Hey thanks for raising!

I think it'd probably just be best to use the [Ruff discussion](https://github.com/astral-sh/ruff/discussions/) section instead. As maintainers, it's a bit harder for us to monitor discussions spread across multiple repositories.

**Comment by charliermarsh** [comment]
Yeah that sounds right to me. Ideally this project would be part of the Ruff monorepo but IIRC it has to be separate for pre-commit reasons :)
