### ISSUE TITLE
Format Python code in documentation files

### ISSUE THREAD

**Issue by niccolomineo** [astral-sh/ruff-pre-commit#55]
I am wondering if the `format check` pre-commit hook can deal with Python code blocks in Markdown, reStructuredText, and LaTex files, like the [blacken-docs](https://github.com/adamchainz/blacken-docs) hook, and, if not, whether you are planning to add such a capability at some point.

**Comment by zanieb** [comment]
We don't support this yet. Related https://github.com/astral-sh/ruff/issues/3792

**Comment by MichaReiser** [comment]
I'm going to close this issue in favor of https://github.com/astral-sh/ruff/issues/8237
