### ISSUE TITLE
v0.1.13 is incorrectly tagged

### ISSUE THREAD

**Issue by edgarrmondragon** [astral-sh/ruff-pre-commit#63]
v0.1.13 points to commit https://github.com/astral-sh/ruff-pre-commit/commit/0511de30af7a3bb94773d285f6891ea8bf41771f (the same as v0.1.12), but it should probably reference https://github.com/astral-sh/ruff-pre-commit/commit/abe8946973726245279f972c708ebcd6ae0ec272.

**Comment by charliermarsh** [comment]
Thanks, sorry, I messed it up.

**Comment by asottile** [comment]
@charliermarsh please next time don't force push tags -- pre-commit uses the revision as its cache key -- next time instead push something like `v0.1.13-1`

**Comment by charliermarsh** [comment]
Will do, sorry about that.
