### ISSUE TITLE
Ruff is run on untracked files despite not being staged.

### ISSUE THREAD

**Issue by LoganPrice344** [astral-sh/ruff-pre-commit#89]
I have run into an issue while attempting to commit changes to my code, where ruff will run on untracked files despite them not being staged.

**Comment by charliermarsh** [comment]
Are you seeing this consistently? Can you produce a reproducible example? Ruff doesn't have much control over this -- Ruff just formats the files that are passed to it by pre-commit.

**Comment by LoganPrice344** [comment]
Yes anytime I create a new file and it contains any ruff error, it will get flagged when pre-commit runs even when the file is not staged.

**Comment by pbastia** [comment]
I'm seeing the same behaviour

**Comment by zanieb** [comment]
Please provide a minimal reproducible example. You may also need to report this upstream i.e. at `pre-commit`. As Charlie mentioned, there's not much complexity in Ruff's handling here.

**Comment by LoganPrice344** [comment]
I have created a repo with a minimal reproducible example on this [repo](https://github.com/LoganPrice344/ExampleRuff). The README has instructions on how  to reproduce the issue.

**Comment by LoganPrice344** [comment]
Ah thank you! That worked!

**Comment by charliermarsh** [comment]
Thanks @dhruvmanila, and thanks for the repo @LoganPrice344.
