### ISSUE TITLE
Release notes link for v0.5.0 is broken

### ISSUE THREAD

**Issue by Tenzer** [astral-sh/ruff-pre-commit#91]
The link to release notes in the v0.5.0 release on this repository is broken: https://github.com/astral-sh/ruff-pre-commit/releases/tag/v0.5.0. It's not the case of the previous releases.

It looks like the upstream repository has dropped the leading "v" in the release/tag names: https://github.com/astral-sh/ruff/releases.

I don't know if this repository is supposed to follow suit in order to match, or if the missing "v" on the Ruff repository is a one-off mistake.

**Comment by MichaReiser** [comment]
Thanks. I updated the release notes but we also have to update the CI action to create the correct changelog entry for upcoming releases:

https://github.com/astral-sh/ruff-pre-commit/blob/1dc9eb131c2ea4816c708e4d85820d2cc8542683/.github/workflows/main.yml#L58-L61

**Comment by Tenzer** [comment]
I've made a PR now to fix that, #92.

**Comment by charliermarsh** [comment]
Thanks!
