### ISSUE TITLE
Is there a way to synchronise Ruff version in ruff-pre-commit with Ruff version in project dependencies?

### ISSUE THREAD

**Issue by bolinocroustibat** [astral-sh/ruff-pre-commit#97]
Is there a way to synchronise Ruff version in ruff-pre-commit with Ruff version in `pyproject.toml` project dependencies?
Can we use the local Ruff in ruff-pre-commit for that?

**Comment by MichaReiser** [comment]
Not to my knowledge. You could try to write a [custom hook](https://dev.to/techishdeep/maximize-your-python-efficiency-with-pre-commit-a-complete-but-concise-guide-39a5) and e.g. use `uv` to run `ruff.

**Comment by AlexWaygood** [comment]
In most of my projects I use [renovate](https://docs.renovatebot.com/) for automated dependency-update PRs. An advantage over e.g. dependabot is that it supports updating dependencies in pre-commit configuration files as well as dependencies in pyproject.toml files, so you can get a single PR that updates the Ruff dependencies in both locations at the same time. (However, while I've never had any problems with renovate's pre-commit support, note that the pre-commit maintainers themselves are not particularly fond of renovate, so it's [not a method that's officially endorsed by pre-commit](https://docs.renovatebot.com/modules/manager/pre-commit/#additional-information) of keeping your pre-commit dependencies up to date.)

Other than that kind of automated dependency update, I don't think there's any way of keeping them automatically in sync other than writing a custom test script that parses the YAML and TOML files and compares the Ruff pins.
